{
 "title": "Home Energy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(homey_device_counter_compressor_starts{name=\"HOME\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    { "expr": "homey_device_degree_minutes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Out Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "DM" } },
   "targets": [
    {
     "expr": "increase(homey_device_degree_minutes{name=\"HOME\"}[$__rate_interval])",
     "legendFormat": "DegreeMinutes"
    },
    {
     "expr": "homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"}",
     "legendFormat": "OutDoor Temp"
    }
   ]
  },
  {
   "title": "Total Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$A*4", "type": "math" }
   ]
  },
  {
   "title": "Temp vs. Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(name) (homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "increase(homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg. Energy/24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Out Temp vs Energy Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Out Temp vs Energy Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"} * -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Energy per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(homey_device_meter_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power used now",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_measure_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Overall Wattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homey_device_measure_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "homey_device_measure_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}