{
 "title": "MinerDashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_tot_time_elapsed", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total HashRate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_tot_MHS_5s" }
   ]
  },
  {
   "title": "Best Share",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_tot_BestShare" }
   ]
  },
  {
   "title": "Found Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_Found_Blocks", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Pools Stale",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_tot_Pool_Stale" }
   ]
  },
  {
   "title": "Accepted Shares",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_tot_accepted_shares" }
   ]
  },
  {
   "title": "Rejected Shares",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_tot_Rejected_shares" }
   ]
  },
  {
   "title": "PowerConsumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "homey_device_measure_power", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(temperature_asic_celsius)" }
   ]
  },
  {
   "title": "miningPi Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_system_celsius", "legendFormat": "{{location}}" }
   ]
  },
  { "title": "OverView HashRate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total HashRate over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "targets": [
    { "expr": "miner_tot_MHS_5s", "legendFormat": "ASIC{{__name__}}" }
   ]
  },
  {
   "title": "Device Hasrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "targets": [
    { "expr": "miner_hshrte", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Asic Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_stat", "legendFormat": "ASIC{{id}}" }
   ]
  },
  {
   "title": "Device Last Well",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_notify_lastWell*1000", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Current Hashrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miner_hshrte", "legendFormat": "ASIC{{id}}" }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature_asic_celsius", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_asic_celsius", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Notify",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Overheat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "miner_notify_DevOverheat", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Miner Staus over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "miner_stat", "legendFormat": "ASIC{{id}}" }
     ]
    },
    {
     "title": "Thermal Cutoff",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "miner_notify_DevScikThermalCutoff",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Last Not Well",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "miner_notify_lastNotWell", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Device Coms Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "miner_notify_DeviceComsError", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Device Dead Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "miner_notify_DeviceDeadIdle600s",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Device Sick Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "miner_notify_devSickIdle", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Thread Zero Hash",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "miner_notify_ThreadZeroHash", "legendFormat": "{{id}}" }
     ]
    }
   ]
  }
 ]
}