{
 "title": "Nibe",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "homey_device_measure_power_addition_electrical_addition_power",
     "legendFormat": "Electrical Addition"
    },
    {
     "expr": "homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"} * -1",
     "legendFormat": "OutDoor Temp"
    }
   ]
  },
  {
   "title": "Compressor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_frequency_current_compressor",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Electrical Addition",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_measure_power_addition_electrical_addition_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Defrosting Decrease from Reference",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_percentage_defrosting_decrease_from_reference",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressor (Hz)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homey_device_frequency_current_compressor",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressor Frequency vs. Inv. Degree Minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "homey_device_frequency_current_compressor",
     "legendFormat": "Compressor Frequency"
    },
    {
     "expr": "homey_device_degree_minutes * -1",
     "legendFormat": "Degree Minutes"
    }
   ]
  },
  {
   "title": "Compressor Freq vs. Invert Out Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "homey_device_measure_temperature{name=\"Aqara Temp Ventilation2\"} * -1",
     "legendFormat": "Temp Ute "
    },
    {
     "expr": "homey_device_frequency_current_compressor",
     "legendFormat": "Compressor Hz"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "homey_device_frequency_current_compressor",
     "legendFormat": "Compressor"
    },
    {
     "expr": "homey_device_measure_power{name=\"Home Energy Meter Gen5 (1 & 3 Clamp)\"}",
     "legendFormat": "power"
    }
   ]
  },
  {
   "title": "Indoor Temp vs. Flow Medium Temp ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "homey_device_measure_temperature_calculated_flow_temp",
     "legendFormat": "Calculated Flow Temp (S1)"
    },
    {
     "expr": "homey_device_measure_temperature_heat_medium_flow",
     "legendFormat": "Heat Medium Flow (BT2)"
    },
    {
     "expr": "homey_device_measure_temperature_inside",
     "legendFormat": "room temperature (BT50)"
    },
    {
     "expr": "homey_device_measure_temperature_avg_outside",
     "legendFormat": "avg. outdoor temp BT1"
    }
   ]
  },
  {
   "title": "Air Velocity vs. Reference",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "homey_device_counter_defrosting_reference_air_velocity_sensor",
     "legendFormat": "AirVelocity Reference"
    },
    {
     "expr": "homey_device_counter_defrosting_value_air_velocity_sensor{name=\"HOME\"}",
     "legendFormat": "AirVelocity"
    }
   ]
  },
  {
   "title": "Condenser Out vs. Return",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "homey_device_measure_temperature_condenser_out",
     "legendFormat": "Condenser Out"
    },
    {
     "expr": "homey_device_measure_temperature_condenser_return",
     "legendFormat": "Condenser Return"
    }
   ]
  }
 ]
}